# Generated by Django 2.0.13 on 2020-08-31 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0002_auto_20200707_2341'),
        ('work', '0003_auto_20200819_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('changed_date', models.DateField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metainfo', to='valueaccounting.EconomicAgent')),
            ],
            options={
                'ordering': ('agent', '-changed_date'),
            },
        ),
    ]
